### ISSUE TITLE
Choosing Noke as an Available Provider Crashes Slock.it

### ISSUE THREAD

**Issue by Quaternioneer** [slockit/usn-mvp#11]
I'm running:

Android version: 4.4.111
Access control: cloud

Slock.it app crashes after I select Noke as one of the available cloud providers. The problem persists after restarting Android, and I have repeated the crash several times.

**Comment by nomoreboredom** [comment]
Hi @Quaternioneer 

Thanks for reporting the issue.
Integration of Noke Padlock is not complete, so it should not be listed there at the first place anyway :)

I am taking it out of the list for now, but we are targeting to complete the integration mid July, so you can expect Noke bundled within late July/early August release.

Thanks again!
