### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by CodeDecent** [slockit/usn-mvp#12]
Android 8
LG G6

Opened app on latest Android update and it just crashes on welcome screen. Tried on two phones. It shows an error for 1 second about an ens domain which Im guessing is where the contract was?

**Comment by nomoreboredom** [comment]
Hi @CodeDecent 

A new version with the fix is released now (version 0.0.27) and available on android playstore, feel free to submit another issue if you experience the same. 

I am closing this issue.
