### ISSUE TITLE
Changing Slock Price JSON Error

### ISSUE THREAD

**Issue by CodeDecent** [slockit/usn-mvp#6]
Android 8 Stable
Cloud/Slock.it

Created a slock for $3 and turned into 192mketh. Cant rent it a that high so edited the price to $3 and got this json error:

Alert
TypeError: undefined is not an object (evaluating 'a.props.navigation.state.params.data.price.timeunit')

**Comment by CodeDecent** [comment]
I click ok but cant continue.

**Comment by nomoreboredom** [comment]
Hi @DigitalA1 

Thanks for reporting the issue, the fix is implemented and will be available with the next release.
